#ifdef XCNIMAGEMANAGEMENT_XCNIMAGEMANAGEMENT_H
#define XCNIMAGEMANAGEMENT_XCNIMAGEMANAGEMENT_H

#ifndef XIMAGEMANAGEMENTDBMANAGEMENT_EXPORT
#define XIMAGEMANAGEMENTDBMANAGEMENT_EXPORT
#endif // !XIMAGEMANAGEMENTDBMANAGEMENT_EXPORT


class CXCNImageManagement
{
public:
	CXCNImageManagement() = default;
	~CXCNImageManagement() = default;

private:

};

#endif // XCNIMAGEMANAGEMENT_XCNIMAGEMANAGEMENT_H
